#!/usr/bin/python
# -*- coding: UTF-8 -*-

try:
    from pychess.Utils.const import prefix
except ImportError:
    print "ERROR: Could not import modules."
    print "Please try to run pychess as stated in the INSTALL file"
    import sys
    sys.exit(1)
    
import gettext, gtk.glade
gettext.install("pychess", localedir=prefix("lang"), unicode=1)
gtk.glade.bindtextdomain("pychess", prefix("lang"))
gtk.glade.textdomain("pychess")

import pychess.Main
pychess.Main.run()
