#!/usr/bin/python
# -*- coding: UTF-8 -*-

from pychess.Utils.const import prefix
import gettext, gtk.glade
gettext.install("pychess", localedir=prefix("lang"), unicode=1)
gtk.glade.bindtextdomain("pychess", prefix("lang"))
gtk.glade.textdomain("pychess")

import pychess.Main
pychess.Main.run()
