import platform
import sys
from collections import namedtuple


# Constants
PYTHONBIN = sys.executable.split("/")[-1]

BITNESS = "64" if platform.machine().endswith('64') else "32"

if sys.platform == "win32":
    stockfish_name = "stockfish_9_x%s.exe" % BITNESS
    sjaakii_name = "sjaakii_win%s_ms.exe" % BITNESS
else:
    stockfish_name = "stockfish"
    sjaakii_name = "sjaakii"


# List of known interpreters
VM = namedtuple('VM', 'name, ext, args')
VM_LIST = [
    VM("node", ".js", None),
    VM("java", ".jar", ["-jar"]),
    VM(PYTHONBIN, ".py", ["-u"])
]


# List of engines later sorted by descending length of name
ENGINE = namedtuple('ENGINE', 'name, protocol, country, depthDependent')
ENGINES_LIST = [
    # -- Full names for internal processing
    ENGINE("PyChess.py", "xboard", "dk", True),
    ENGINE("pychess-engine", "xboard", "dk", True),
    ENGINE(stockfish_name, "uci", "no", False),
    ENGINE(sjaakii_name, "xboard", "nl", False),
    ENGINE("Houdini.exe", "uci", "be", False),
    ENGINE("Rybka.exe", "uci", "cz", False),

    # -- Names from CCRL 40/4
    ENGINE("stockfish", "uci", "no", False),
    ENGINE("houdini", "uci", "be", False),
    ENGINE("komodo", "uci", "us", False),
    ENGINE("fire", "uci", "us", False),
    ENGINE("fizbo", "uci", "us", False),
    ENGINE("shredder", "uci", "de", False),
    ENGINE("andscacs", "uci", "ad", False),
    ENGINE("gull", "uci", "ru", False),
    ENGINE("booot", "uci", "ua", False),  # Formerly XB
    ENGINE("equinox", "uci", "it", False),
    ENGINE("chiron", "uci", "it", False),  # Allows XB
    ENGINE("critter", "uci", "sk", False),
    ENGINE("hannibal", "uci", "us", False),
    ENGINE("fritz", "uci", "nl", False),
    ENGINE("nirvana", "uci", "us", False),
    ENGINE("texel", "xboard", "se", False),  # UCI is an option in the command line
    ENGINE("rybka", "uci", "cz", False),
    ENGINE("blackmamba", "uci", "it", False),
    # ivanhoe, robbolito, panchess, bouquet
    ENGINE("senpai", "uci", "fr", False),
    ENGINE("laser", "uci", "us", False),
    ENGINE("naum", "uci", "rs", False),
    ENGINE("arasan", "uci", "us", False),
    ENGINE("strelka", "uci", "ru", False),
    ENGINE("pedone", "uci", "it", False),
    ENGINE("vajolet", "uci", "it", False),
    ENGINE("protector", "uci", "de", False),
    ENGINE("ethereal", "uci", "us", False),
    ENGINE("defenchess", "uci", "tr", False),
    ENGINE("nemorino", "uci", "de", False),  # Allows XB
    ENGINE("hiarcs", "uci", "gb", False),
    # ice @de (name too short)
    ENGINE("smarthink", "uci", "ru", False),  # Allows XB
    ENGINE("xiphos", "uci", "us", False),
    ENGINE("wasp", "uci", "us", False),
    ENGINE("cheng", "uci", "cz", False),
    ENGINE("crafty", "xboard", "us", False),
    ENGINE("bobcat", "uci", "nl", False),
    ENGINE("rodent", "uci", "pl", False),
    ENGINE("spike", "uci", "de", False),  # Allows XB
    ENGINE("alfil", "uci", "es", False),
    ENGINE("spark", "uci", "nl", False),
    ENGINE("junior", "uci", "il", False),
    ENGINE("hakkapeliitta", "uci", "fi", False),
    ENGINE("exchess", "xboard", "us", False),
    ENGINE("demolito", "uci", "fr", False),
    ENGINE("tucano", "xboard", "br", False),
    ENGINE("scorpio", "xboard", "et", False),
    ENGINE("chessbrain", "uci", "de", False),  # Allows XB
    ENGINE("gaviota", "xboard", "ar", False),
    ENGINE("zappa", "uci", "us", False),
    ENGINE("togaii", "uci", "de", False),
    ENGINE("toga2", "uci", "de", False),
    ENGINE("chess22k", "uci", "nl", False),
    ENGINE("amoeba", "uci", "fr", False),
    ENGINE("onno", "uci", "de", False),
    ENGINE("thinker", "uci", "ca", False),
    ENGINE("sjeng", "xboard", "be", False),
    ENGINE("disasterarea", "uci", "de", False),
    ENGINE("atlas", "uci", "es", False),
    ENGINE("minko", "uci", "sv", False),
    ENGINE("discocheck", "uci", "fr", False),
    ENGINE("bright", "uci", "nl", False),
    ENGINE("daydreamer", "uci", "us", False),
    ENGINE("quazar", "uci", "ru", False),
    ENGINE("zurichess", "uci", "ro", False),
    ENGINE("deuterium", "uci", "ph", False),
    ENGINE("murka", "uci", "by", False),
    ENGINE("loop", "uci", "de", False),
    ENGINE("dirty", "xboard", "es", False),
    ENGINE("nemo", "uci", "de", False),
    ENGINE("tornado", "uci", "de", False),
    ENGINE("bugchess", "xboard", "fr", False),
    ENGINE("baron", "xboard", "nl", False),
    ENGINE("octochess", "uci", "de", False),  # Allows XB
    ENGINE("gnuchessu", "uci", "us", False),
    ENGINE("gnuchess", "xboard", "us", False),
    ENGINE("rhetoric", "uci", "es", False),
    ENGINE("ktulu", "uci", "ir", False),  # Allows XB
    ENGINE("ruydos", "uci", "es", False),
    ENGINE("prodeo", "uci", "nl", False),  # Allows XB
    ENGINE("twisted-logic", "uci", "ph", False),
    ENGINE("frenzee", "xboard", "dk", False),
    ENGINE("pawny", "uci", "bg", False),
    ENGINE("gogobello", "uci", "it", False),
    ENGINE("jonny", "uci", "de", False),  # Formerly XB
    ENGINE("chessmaster", "xboard", "nl", False),
    ENGINE("shield", "uci", "it", False),
    ENGINE("godel", "uci", "es", False),  # May allow XB
    ENGINE("karballo", "uci", "es", False),
    ENGINE("chronos", "uci", "ar", False),
    ENGINE("devel", "uci", "no", False),
    ENGINE("cheese", "uci", "fr", False),  # Allows XB
    ENGINE("tiger", "uci", "gp", False),
    ENGINE("marvin", "uci", "se", False),  # Allows XB
    ENGINE("pharaon", "uci", "fr", False),  # Allows XB
    ENGINE("redqueen", "uci", "br", False),
    ENGINE("arminius", "xboard", "de", False),
    ENGINE("delfi", "uci", "it", False),  # Allows XB
    ENGINE("gandalf", "uci", "dk", False),  # Allows XB
    ENGINE("djinn", "xboard", "us", False),
    ENGINE("alaric", "uci", "se", False),  # Allows XB
    ENGINE("ece-x3", "uci", "it", False),
    ENGINE("nebula", "uci", "rs", False),
    ENGINE("naraku", "uci", "it", False),
    ENGINE("phalanx", "xboard1", "cz", False),
    ENGINE("donna", "uci", "us", False),
    ENGINE("greko", "uci", "ru", False),
    ENGINE("colossus", "uci", "gb", False),
    ENGINE("cyrano", "uci", "no", False),
    ENGINE("sjakk", "uci", "no", False),
    ENGINE("et_chess", "xboard2", "fr", False),
    ENGINE("rodin", "xboard", "es", False),
    ENGINE("wyldchess", "uci", "in", False),  # Allows XB
    ENGINE("movei", "uci", "il", False),  # Allows XB
    ENGINE("wildcat", "uci", "by", False),  # Formerly XB
    ENGINE("philou", "uci", "fr", False),
    ENGINE("rotor", "uci", "nl", False),
    ENGINE("sloppy", "xboard", "fi", False),
    ENGINE("zarkov", "xboard", "us", False),
    ENGINE("schess", "uci", "us", False),  # Allows XB
    ENGINE("sblitz", "uci", "us", False),  # Allows XB
    ENGINE("delocto", "uci", "at", False),
    ENGINE("noragrace", "xboard", "us", False),
    ENGINE("ruffian", "uci", "se", False),
    ENGINE("glass", "uci", "pl", False),
    ENGINE("jellyfish", "uci", "unknown", False),  # Allows XB
    ENGINE("garbochess", "uci", "us", False),
    ENGINE("amyan", "uci", "cl", False),  # Allows XB
    ENGINE("lemming", "xboard", "us", False),
    ENGINE("danasah", "uci", "es", False),  # Allows XB
    ENGINE("monolith", "uci", "it", False),
    # k2 @ru (name to short)
    # n2 @de (name to short)
    ENGINE("floyd", "uci", "nl", False),
    ENGINE("muse", "xboard", "ch", False),  # May support UCI as well
    ENGINE("cuckoo", "xboard", "se", False),  # UCI is an option in the command line
    ENGINE("francesca", "xboard", "gb", False),
    ENGINE("hamsters", "uci", "it", False),
    ENGINE("counter", "uci", "ru", False),
    # sos @de (name too short)
    ENGINE("pseudo", "xboard", "cz", False),
    ENGINE("aristarch", "uci", "de", False),
    ENGINE("maverick", "uci", "gb", False),
    ENGINE("capivara", "uci", "br", False),
    ENGINE("petir", "xboard", "id", False),
    ENGINE("nanoszachy", "xboard", "pl", False),
    ENGINE("brutus", "xboard", "nl", False),
    ENGINE("ghost", "xboard", "de", False),
    ENGINE("anaconda", "uci", "de", False),
    ENGINE("rebel", "uci", "nl", False),
    ENGINE("hermann", "uci", "de", False),
    ENGINE("anmon", "uci", "fr", False),
    ENGINE("pupsi", "uci", "se", False),
    ENGINE("ufim", "uci", "ru", False),  # Formerly XB
    ENGINE("fridolin", "uci", "de", False),  # Allows XB
    ENGINE("jikchess", "xboard2", "fi", False),
    ENGINE("betsabe", "xboard", "es", False),
    ENGINE("pepito", "xboard", "es", False),
    ENGINE("schooner", "xboard", "ca", False),
    ENGINE("danchess", "xboard", "et", False),
    ENGINE("tomitank", "uci", "hu", False),
    ENGINE("greenlight", "xboard", "gb", False),
    ENGINE("goliath", "uci", "de", False),
    ENGINE("trace", "xboard", "au", False),
    ENGINE("yace", "uci", "de", False),  # Allows XB
    ENGINE("coiled", "uci", "es", False),
    ENGINE("dorky", "xboard", "us", False),
    ENGINE("cyberpagno", "xboard", "it", False),
    ENGINE("drosophila", "xboard", "se", False),
    ENGINE("bruja", "xboard", "us", False),
    ENGINE("magnum", "uci", "ca", False),
    ENGINE("bagatur", "uci", "bg", False),
    # tao @nl (name too short)
    ENGINE("delphil", "uci", "fr", False),
    ENGINE("bbchess", "uci", "si", False),
    ENGINE("mephisto", "uci", "gb", False),
    ENGINE("winter", "uci", "ch", False),
    ENGINE("cerebro", "xboard", "it", False),
    ENGINE("gothmog", "uci", "no", False),  # Allows XB
    ENGINE("xpdnt", "xboard", "us", False),
    ENGINE("kiwi", "xboard", "it", False),
    ENGINE("jumbo", "xboard", "de", False),
    ENGINE("anatoli", "xboard", "nl", False),
    ENGINE("pikoszachy", "xboard", "pl", False),
    ENGINE("littlethought", "uci", "au", False),
    ENGINE("bumblebee", "uci", "us", False),
    ENGINE("matacz", "xboard", "pl", False),
    ENGINE("Soldat", "xboard", "it", False),
    ENGINE("spider", "xboard", "nl", False),
    ENGINE("madchess", "uci", "us", False),
    ENGINE("abrok", "uci", "de", False),  # Allows XB
    ENGINE("ares", "uci", "us", False),
    ENGINE("kingofkings", "uci", "ca", False),
    ENGINE("lambchop", "uci", "nz", False),  # Formerly XB
    ENGINE("gromit", "uci", "de", False),
    # shallow
    ENGINE("eeyore", "uci", "ru", False),  # Allows XB
    ENGINE("gaia", "uci", "fr", False),
    ENGINE("nejmet", "uci", "fr", False),  # Allows XB
    ENGINE("romichess", "xboard", "us", False),
    ENGINE("caligula", "uci", "es", False),
    ENGINE("quark", "xboard", "de", False),
    ENGINE("dragon", "xboard", "fr", False),
    ENGINE("nemeton", "xboard", "nl", False),
    ENGINE("snitch", "xboard", "de", False),
    ENGINE("hussar", "uci", "hu", False),
    ENGINE("olithink", "xboard", "de", False),
    ENGINE("orion", "uci", "fr", False),
    ENGINE("typhoon", "xboard", "us", False),
    ENGINE("simplex", "uci", "es", False),
    ENGINE("giraffe", "xboard", "gb", False),
    ENGINE("lozza", "uci", "gb", False),
    ENGINE("teki", "uci", "in", False),
    ENGINE("ifrit", "uci", "ru", False),
    ENGINE("tjchess", "uci", "us", False),  # Allows XB
    ENGINE("knightdreamer", "xboard", "se", False),
    ENGINE("bearded", "xboard", "pl", False),
    ENGINE("postmodernist", "xboard", "gb", False),
    ENGINE("capture", "xboard", "fr", False),
    ENGINE("comet", "xboard", "de", False),
    ENGINE("leila", "xboard", "it", False),
    ENGINE("diablo", "uci", "us", False),
    # amy @de (name too short)
    ENGINE("gosu", "xboard", "pl", False),
    ENGINE("myrddin", "xboard", "us", False),
    ENGINE("patzer", "xboard", "de", False),
    ENGINE("jazz", "xboard", "nl", False),
    ENGINE("bringer", "xboard", "de", False),
    ENGINE("cmcchess", "uci", "zh", False),
    ENGINE("terra", "uci", "se", False),
    ENGINE("crazybishop", "xboard", "fr", False),  # Named as tcb
    ENGINE("homer", "uci", "de", False),
    ENGINE("betsy", "xboard", "us", False),
    ENGINE("dimitri", "uci", "it", False),  # May allow XB
    ENGINE("amateur", "xboard", "us", False),
    ENGINE("alex", "uci", "us", False),
    ENGINE("tigran", "uci", "es", False),
    ENGINE("plisk", "uci", "us", False),  # Allows XB
    ENGINE("horizon", "xboard", "us", False),
    ENGINE("queen", "uci", "nl", False),  # Allows XB
    ENGINE("arion", "uci", "fr", False),
    ENGINE("eveann", "xboard", "es", False),
    ENGINE("gibbon", "uci", "fr", False),
    ENGINE("waxman", "xboard", "us", False),
    ENGINE("thor", "xboard", "hr", False),
    ENGINE("sorgenkind", "xboard", "dk", False),
    ENGINE("barbarossa", "uci", "at", False),
    ENGINE("chezzz", "xboard", "dk", False),
    ENGINE("sage", "xboard", "unknown", False),
    ENGINE("absolute-zero", "uci", "zh", False),
    ENGINE("mediocre", "uci", "se", False),
    ENGINE("aice", "xboard", "gr", False),
    # isa @fr (name too short)
    ENGINE("nebiyu", "xboard", "et", False),
    ENGINE("rubichess", "uci", "de", False),
    ENGINE("sungorus", "uci", "es", False),
    ENGINE("galjoen", "uci", "be", False),  # Allows XB
    ENGINE("asterisk", "uci", "hu", False),  # Allows XB
    ENGINE("averno", "xboard", "es", False),
    ENGINE("joker", "xboard", "nl", False),
    ENGINE("tytan", "xboard", "pl", False),
    ENGINE("resp", "xboard", "de", False),
    ENGINE("popochin", "xboard", "es", False),
    ENGINE("knightx", "xboard2", "fr", False),
    ENGINE("fischerle", "uci", "de", False),
    ENGINE("ayito", "uci", "es", False),  # Formerly XB
    ENGINE("chaturanga", "xboard", "it", False),
    ENGINE("matilde", "xboard", "it", False),
    ENGINE("paladin", "uci", "in", False),
    ENGINE("rival", "uci", "gb", False),
    ENGINE("scidlet", "xboard", "nz", False),
    ENGINE("butcher", "xboard", "pl", False),
    # esc @it (name too short)
    ENGINE("kmtchess", "xboard", "es", False),
    ENGINE("natwarlal", "xboard", "in", False),
    ENGINE("zeus", "xboard", "ru", False),
    # doctor @de (unknown protocol)
    ENGINE("firefly", "uci", "hk", False),
    ENGINE("napoleon", "uci", "it", False),
    ENGINE("robocide", "uci", "gb", False),
    ENGINE("ct800", "uci", "de", False),
    # ant @nl (name too short)
    ENGINE("gopher_check", "uci", "us", False),
    ENGINE("anechka", "uci", "ru", False),
    ENGINE("alichess", "uci", "de", False),
    ENGINE("dorpsgek", "xboard", "en", False),
    ENGINE("joker2", "uci", "it", False),
    ENGINE("adam", "xboard", "fr", False),
    ENGINE("obender", "xboard", "ru", False),
    ENGINE("zevra", "uci", "ru", False),
    ENGINE("exacto", "xboard", "us", False),
    ENGINE("buzz", "xboard", "us", False),
    ENGINE("ramjet", "uci", "it", False),
    ENGINE("chessalex", "uci", "ru", False),
    ENGINE("chispa", "uci", "ar", False),  # Allows XB
    ENGINE("beowulf", "xboard", "gb", False),
    ENGINE("rattate", "xboard", "it", False),
    ENGINE("latista", "xboard", "us", False),
    ENGINE("sinobyl", "xboard", "us", False),
    ENGINE("sjaakii", "xboard", "nl", False),
    ENGINE("ng-play", "xboard", "gr", False),
    ENGINE("feuerstein", "uci", "de", False),
    # uralochka (blacklisted)
    ENGINE("neurosis", "xboard", "nl", False),
    ENGINE("madeleine", "uci", "it", False),  # Allows XB
    ENGINE("atak", "xboard", "pl", False),
    ENGINE("mango", "xboard", "ve", False),
    ENGINE("protej", "uci", "it", False),
    ENGINE("genesis", "xboard", "il", False),
    ENGINE("baislicka", "uci", "unknown", False),
    ENGINE("blackbishop", "uci", "de", False),  # Allows XB
    ENGINE("inmichess", "xboard", "at", False),
    ENGINE("kurt", "xboard", "de", False),
    ENGINE("blitzkrieg", "uci", "in", False),
    ENGINE("nagaskaki", "xboard", "za", False),
    ENGINE("chesley", "xboard", "us", False),
    ENGINE("alarm", "xboard", "se", False),
    ENGINE("lime", "uci", "gb", False),  # Allows XB
    ENGINE("uragano", "xboard", "it", False),
    ENGINE("sunsetter", "xboard", "de", False),
    ENGINE("tinychess", "uci", "unknown", False),
    ENGINE("chesskiss", "xboard", "unknown", False),
    ENGINE("fortress", "xboard", "it", False),
    ENGINE("nesik", "xboard", "pl", False),
    ENGINE("clever-girl", "uci", "us", False),
    ENGINE("wjchess", "uci", "fr", False),
    ENGINE("prophet", "xboard", "us", False),
    # gk @nl (name too short)
    # alf @dk (name too short)
    ENGINE("knockout", "xboard", "de", False),
    ENGINE("bikjump", "uci", "nl", False),
    ENGINE("wing", "xboard", "nl", False),
    ENGINE("clarabit", "uci", "es", False),  # Allows XB
    ENGINE("adroitchess", "uci", "gb", False),
    ENGINE("parrot", "xboard", "us", False),
    ENGINE("abbess", "xboard", "us", False),
    ENGINE("alcibiades", "uci", "bg", False),
    ENGINE("gunborg", "uci", "unknown", False),
    ENGINE("matheus", "uci", "br", False),  # Allows XB
    ENGINE("monarch", "uci", "gb", False),
    ENGINE("chessmind", "uci", "de", False),
    ENGINE("dolphin", "xboard", "vn", False),
    ENGINE("kingsout", "xboard", "de", False),
    ENGINE("bodo", "uci", "au", False),
    ENGINE("crabby", "uci", "us", False),
    ENGINE("vice", "uci", "unknown", False),
    ENGINE("gerbil", "xboard", "us", False),
    ENGINE("rdchess", "xboard", "at", False),
    # ax @vn (name too short)
    ENGINE("cinnamon", "uci", "it", False),
    # plp @no (name too short)
    ENGINE("jabba", "uci", "gb", False),
    ENGINE("plywood", "xboard", "unknown", False),
    ENGINE("bestia", "xboard", "ua", False),
    ENGINE("prochess", "uci", "it", False),
    ENGINE("zetadva", "xboard", "de", False),
    # zct @us (name too short)
    ENGINE("little-wing", "uci", "fr", False),  # Allows XB
    ENGINE("freyr", "xboard", "ro", False),
    ENGINE("embla", "uci", "nl", False),
    ENGINE("cupcake", "xboard", "us", False),
    ENGINE("delphimax", "uci", "de", False),
    ENGINE("oberon", "xboard", "pl", False),
    ENGINE("ecce", "uci", "ru", False),
    ENGINE("ceibo", "uci", "ar", False),
    ENGINE("requiem", "xboard", "fi", False),
    ENGINE("bismark", "uci", "il", False),
    ENGINE("leonidas", "xboard", "nl", False),
    ENGINE("snowy", "uci", "us", False),
    ENGINE("small potato", "xboard", "at", False),
    ENGINE("elephant", "xboard", "de", False),
    ENGINE("biglion", "uci", "cm", False),
    ENGINE("frank-walter", "xboard", "nl", False),
    ENGINE("gullydeckel", "xboard", "de", False),
    ENGINE("armageddon", "xboard", "pl", False),
    ENGINE("slibo", "xboard", "de", False),
    ENGINE("bubble", "uci", "br", False),
    ENGINE("arabian-knight", "xboard", "pl", False),
    ENGINE("faile", "xboard1", "ca", False),
    ENGINE("hedgehog", "uci", "ru", False),
    ENGINE("matant", "xboard", "pl", False),
    ENGINE("ladameblanche", "xboard", "fr", False),
    ENGINE("ssechess", "xboard", "us", False),
    ENGINE("cilian", "xboard", "ch", False),
    ENGINE("etude", "uci", "us", False),
    ENGINE("chess4j", "xboard", "us", False),
    # eia @ru (name too short)
    ENGINE("monik", "xboard", "unknown", False),
    ENGINE("alchess", "uci", "ru", False),
    ENGINE("sissa", "uci", "fr", False),
    # bsc @fr (name too short)
    ENGINE("micro-max", "xboard", "nl", False),
    ENGINE("mustang", "xboard", "by", False),
    ENGINE("janwillem", "xboard", "nl", False),
    ENGINE("sharper", "xboard", "se", False),
    ENGINE("bibichess", "uci", "fr", False),
    ENGINE("smash", "uci", "it", False),
    ENGINE("smirf", "xboard", "de", False),
    ENGINE("heracles", "uci", "fr", False),
    ENGINE("samchess", "xboard", "us", False),
    ENGINE("iach", "xboard", "unknown", False),
    ENGINE("dabbaba", "xboard", "dk", False),
    ENGINE("bambam", "xboard", "at", False),
    ENGINE("eagle", "uci", "uci", False),
    ENGINE("clueless", "uci", "de", False),
    ENGINE("warrior", "xboard", "lv", False),
    ENGINE("claudia", "uci", "es", False),
    ENGINE("morphy", "xboard", "us", False),
    ENGINE("snailchess", "xboard", "sg", False),
    ENGINE("tyrell", "uci", "us", False),
    # freechess @ru (blacklisted)
    ENGINE("mrchess", "xboard", "sg", False),
    ENGINE("surprise", "xboard", "de", False),
    ENGINE("purplehaze", "xboard", "fr", False),
    ENGINE("simontacchi", "uci", "us", False),
    ENGINE("butter", "uci", "unknown", False),
    ENGINE("presbyter", "uci", "unknown", False),  # Allows XB
    ENGINE("roce", "uci", "ch", False),
    ENGINE("deepov", "uci", "fr", False),
    ENGINE("ranita", "uci", "fr", False),
    ENGINE("sayuri", "uci", "jp", False),
    ENGINE("matmoi", "xboard", "ca", False),
    ENGINE("ajedreztactico", "xboard", "mx", False),
    ENGINE("heavychess", "uci", "ar", False),
    ENGINE("celes", "uci", "nl", False),
    ENGINE("rataaeroespacial", "xboard", "ar", False),
    ENGINE("jars", "xboard", "fr", False),
    ENGINE("ziggurat", "uci", "us", False),
    ENGINE("noonian", "uci", "us", False),
    ENGINE("predateur", "uci", "fr", False),
    ENGINE("skiull", "uci", "ve", False),
    ENGINE("chenard", "xboard", "us", False),
    ENGINE("beaches", "xboard", "us", False),
    ENGINE("pigeon", "uci", "ca", False),
    ENGINE("milady", "xboard", "fr", False),
    ENGINE("enigma", "xboard", "pl", False),
    ENGINE("hoichess", "xboard", "de", False),
    ENGINE("mobmat", "uci", "us", False),
    ENGINE("macromix", "uci", "ua", False),
    ENGINE("cecir", "xboard", "uy", False),
    ENGINE("grizzly", "xboard", "de", False),
    ENGINE("embracer", "xboard", "se", False),
    ENGINE("bremboce", "xboard", "it", False),
    ENGINE("fauce", "xboard", "it", False),
    ENGINE("berochess", "uci", "de", False),
    ENGINE("pulsar", "xboard", "us", False),
    ENGINE("robin", "xboard", "pl", False),
    ENGINE("mint", "xboard", "se", False),
    ENGINE("lodocase", "xboard", "be", False),
    ENGINE("laurifer", "xboard", "pl", False),
    ENGINE("rocinante", "uci", "es", False),
    # elf @tr (name too short)
    ENGINE("ziggy", "uci", "is", False),
    ENGINE("vicki", "xboard", "za", False),
    ENGINE("kanguruh", "xboard", "at", False),
    ENGINE("adamant", "xboard", "ru", False),
    ENGINE("gchess", "xboard", "it", False),
    ENGINE("kitteneitor", "xboard", "es", False),
    ENGINE("zzzzzz", "xboard", "nl", False),
    ENGINE("zoidberg", "xboard", "es", False),
    # see @au (name too short)
    ENGINE("aldebaran", "xboard", "it", False),
    ENGINE("tscp", "xboard", "us", False),
    ENGINE("jaksah", "uci", "rs", False),  # Allows XB
    ENGINE("enkochess", "uci", "unknown", False),
    ENGINE("tristram", "xboard", "us", False),
    ENGINE("testina", "uci", "it", False),
    # chess @it (name too generic)
    ENGINE("gargamella", "xboard", "it", False),
    ENGINE("sharpchess", "xboard", "unknown", False),
    ENGINE("jester", "xboard", "us", False),
    ENGINE("bace", "xboard", "us", False),
    ENGINE("mizar", "xboard", "it", False),
    ENGINE("polarchess", "xboard", "no", False),
    ENGINE("golem", "xboard", "it", False),
    ENGINE("pleco", "uci", "us", False),
    ENGINE("belzebub", "xboard", "pl", False),
    ENGINE("dchess", "xboard", "us", False),
    ENGINE("adachess", "xboard", "it", False),
    ENGINE("pooky", "uci", "us", False),
    ENGINE("simon", "xboard", "us", False),
    ENGINE("iq23", "uci", "de", False),
    ENGINE("vapor", "uci", "us", False),
    ENGINE("chessrikus", "xboard", "us", False),
    ENGINE("spartan", "uci", "unknown", False),
    ENGINE("mscp", "xboard", "nl", False),
    ENGINE("storm", "xboard", "us", False),
    ENGINE("kasparov", "uci", "ca", False),
    ENGINE("philemon", "uci", "ch", False),
    ENGINE("revati", "uci", "de", False),
    ENGINE("darky", "uci", "mx", False),
    ENGINE("rainman", "xboard", "se", False),
    ENGINE("saruman", "uci", "unknown", False),
    ENGINE("marginal", "uci", "ru", False),
    ENGINE("pulse", "uci", "ch", False),
    ENGINE("bullitchess", "uci", "unknown", False),
    ENGINE("zotron", "xboard", "us", False),
    ENGINE("violet", "uci", "unknown", False),
    ENGINE("sdbc", "xboard", "de", False),
    ENGINE("damas", "xboard", "br", False),
    ENGINE("needle", "xboard", "fi", False),
    ENGINE("vanilla", "xboard", "au", False),
    ENGINE("cicada", "uci", "us", False),
    ENGINE("hokus", "xboard", "pl", False),
    ENGINE("larsen", "xboard", "it", False),
    ENGINE("mace", "uci", "de", False),
    ENGINE("alibaba", "uci", "nl", False),
    ENGINE("yawce", "xboard", "dk", False),
    ENGINE("apep", "xboard", "us", False),
    ENGINE("supra", "uci", "pt", False),
    ENGINE("koedem", "uci", "de", False),
    ENGINE("piranha", "uci", "de", False),
    ENGINE("tarrasch", "uci", "us", False),
    ENGINE("andersen", "xboard", "se", False),
    ENGINE("gedeone", "xboard", "unknown", False),
    ENGINE("pwned", "uci", "us", False),
    ENGINE("apil", "xboard", "de", False),
    ENGINE("pentagon", "xboard", "it", False),
    ENGINE("roque", "xboard", "es", False),
    ENGINE("numpty", "xboard", "gb", False),
    ENGINE("blikskottel", "xboard", "za", False),
    ENGINE("nero", "xboard", "de", False),
    ENGINE("hactar", "uci", "de", False),
    ENGINE("suff", "uci", "at", False),
    ENGINE("sabrina", "xboard", "it", False),
    ENGINE("satana", "xboard", "it", False),
    ENGINE("tony", "xboard", "ca", False),
    ENGINE("goyaz", "xboard", "br", False),
    ENGINE("minimardi", "xboard", "unknown", False),
    ENGINE("eden", "uci", "de", False),
    ENGINE("jchess", "xboard", "pl", False),
    ENGINE("nanook", "uci", "fr", False),
    ENGINE("skaki", "xboard", "us", False),
    ENGINE("virutor", "uci", "cz", False),
    ENGINE("minichessai", "xboard", "pl", False),
    ENGINE("joanna", "xboard", "pl", False),
    ENGINE("ozwald", "xboard", "fi", False),
    ENGINE("gladiator", "xboard", "es", False),
    ENGINE("fimbulwinter", "xboard", "us", False),
    ENGINE("cerulean", "xboard", "ca", False),
    ENGINE("killerqueen", "uci", "it", False),
    ENGINE("trex", "uci", "fr", False),
    ENGINE("qutechess", "uci", "si", False),
    ENGINE("tikov", "uci", "gb", False),
    ENGINE("dragontooth", "uci", "us", False),
    ENGINE("raffaela", "xboard", "it", False),
    ENGINE("gringo", "xboard", "at", False),
    ENGINE("toledo-uci", "uci", "mx", True),
    ENGINE("toledo", "xboard", "mx", True),
    ENGINE("pierre", "xboard", "ca", False),
    ENGINE("neurone", "xboard", "it", False),
    ENGINE("gray-matter", "xboard", "unknown", False),
    ENGINE("darkfusch", "uci", "de", False),
    ENGINE("project-invincible", "xboard", "fi", False),
    ENGINE("cassandre", "uci", "fr", False),  # Allows XB
    ENGINE("jchecs", "xboard", "fr", False),
    ENGINE("brama", "xboard", "it", False),
    ENGINE("soberango", "xboard", "ar", False),
    ENGINE("usurpator", "xboard", "nl", False),
    ENGINE("ronja", "xboard", "se", False),
    ENGINE("blitzter", "xboard", "de", False),
    ENGINE("frank", "xboard", "it", False),
    ENGINE("strategicdeep", "xboard", "pl", False),
    ENGINE("talvmenni", "xboard", "fo", False),
    ENGINE("minnow", "uci", "unknown", False),
    ENGINE("xadreco", "xboard", "br", False),
    ENGINE("safrad", "uci", "cz", False),
    ENGINE("giuchess", "xboard", "it", False),
    # zoe (name too short)
    ENGINE("iota", "uci", "gb", False),
    ENGINE("youk", "xboard", "fr", False),
    ENGINE("kace", "xboard", "us", False),
    ENGINE("nsvchess", "uci", "fr", False),
    ENGINE("chad", "uci", "xb", False),
    ENGINE("dreamer", "xboard", "nl", False),
    ENGINE("luzhin", "xboard", "unknown", False),
    ENGINE("dika", "xboard", "fr", False),
    ENGINE("hippocampe", "xboard", "fr", False),
    ENGINE("chessputer", "uci", "unknown", False),
    ENGINE("pyotr", "xboard", "gr", False),
    # easypeasy (no information)
    ENGINE("acqua", "uci", "it", False),
    # neg @nl (name too short)
    # ram @nl (name too short)
    ENGINE("lamosca", "xboard", "it", False),
    # ace @us (name too short)
    # pos @nl (name too short)

    # -- Other (parent engine, derivative work, unlisted, variant engine...)
    ENGINE("s_pro", "uci", "it", False),
    ENGINE("asmfish", "uci", "bg", False),
    ENGINE("glaurung", "uci", "no", False),
    ENGINE("amundsen", "xboard", "se", False),
    ENGINE("anticrux", "uci", "fr", True),
    ENGINE("fairymax", "xboard", "nl", False),
    ENGINE("fruit", "uci", "fr", False)
]


# Bubble sort by descending length of the name
for i in range(len(ENGINES_LIST) - 1, 1, - 1):
    for j in range(0, i - 1):
        if len(ENGINES_LIST[i].name) > len(ENGINES_LIST[j].name):
            tmp = ENGINES_LIST[i]
            ENGINES_LIST[i] = ENGINES_LIST[j]
            ENGINES_LIST[j] = tmp
