#!/bin/sh

cp ~/.config/pychess/config ~/.config/pychess/config.saved
rm ~/.config/pychess/config

cd ~/pychess

LANG=C PYTHONPATH=~/storytext/lib ~/storytext/bin/storytext \
	--interface=gtk3 \
	--mapfiles=testing/storytext/ui_map.conf \
	--record=testing/storytext/"$1" \
./pychess

cp ~/.config/pychess/config.saved ~/.config/pychess/config


