#!/bin/sh

cd ~/pychess
LANG=C PYTHONPATH=~/storytext/lib ~/storytext/bin/storytext \
	--interface=gtk3 \
	--delay=1 \
	--mapfiles=testing/storytext/ui_map.conf \
	--replay=testing/storytext/"$1" \
./pychess
