.TH pychess 1 "December 22, 2006"
.SH NAME
pychess - chess graphical user interface for several chess engines
.SH DESCRIPTION
.PP
pychess provides a fully featured, nice looking, easy to use chess
client for the gnome-desktop.

The client should be usable both to those totally new to chess, and
those who want to use a computer to further enchance their play. 
.PP
.SH Features
.PP
* Tabbed interface
.PP
* pgn+epd read/write support
.PP
* Hints and spymode
.PP
* xboard/cecp engine support 
.PP
* Builtin python based engine
.PP
* Openingbook using Polyglot format
.PP
* Clean interface and dialogs
.PP
* Builtin move validator
.PP
* Legal move highlighting 
.PP
* Supports drag'n'drop.
.SH HOMEPAGE
http://pychess.googlepages.com/home
.SH AUTHOR
This manual page was written by Varun Hiremath <varunhiremath@gmail.com>,
for the Debian project (but may be used by others).
